### ISSUE TITLE
Storage Zones outside original region have their regions in the URL

### ISSUE THREAD

**Issue by johlym** [brandon-meeks/bunny_cdn#1]
https://github.com/brandon-meeks/bunny_cdn/blob/07a5467985ff2207aa3489f62089f0d6abdd2e38/lib/bunny_cdn/storage.rb#L6

For example: while `storage.bunnycdn.com` may work for the original Falkenstein region, if a user has a storage zone in New York, the base URL would be `ny.storage.bunnycdn.com`. 

Considering how to best approach thing, probably through a PR that adds a fresh `config.region` and the base URL is built based on that value.

Thoughts?

**Comment by brandon-meeks** [comment]
Adding the region as a configuration option would probably work best. It would also require possible removal of the BASE_URL overall so the region can be added in.

**Comment by johlym** [comment]
Makes sense. I forked the gem and tweaked it to unblock myself. Let me know what you think: https://github.com/johlym/bunny_cdn
